export const viewerPage = String.raw`<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Live Response</title><style>
:root{font-family:Inter,Segoe UI,sans-serif;color:#e2e8f0;background:#020617;color-scheme:dark}*{box-sizing:border-box}body{margin:0;padding:24px}.shell{width:min(900px,100%);min-height:calc(100vh - 48px);margin:auto;padding:22px;border:1px solid #1e293b;border-radius:16px;background:#0f172a}.head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #1e293b;padding-bottom:14px}h1{margin:0;font-size:20px}.status{font-size:12px;color:#94a3b8}.status.live{color:#34d399}.join{max-width:440px;margin:80px auto}.join label{display:block;margin-bottom:8px;color:#94a3b8}.row{display:flex;gap:8px}input{flex:1;min-width:0;padding:11px;border:1px solid #334155;border-radius:8px;background:#020617;color:#fff;text-transform:uppercase}button{padding:9px 12px;border:1px solid #38bdf8;border-radius:8px;background:#0c4a6e;color:#e0f2fe;cursor:pointer}.error{color:#fda4af;margin-top:10px}.response-head{display:flex;justify-content:flex-end;margin:14px 0}.response{line-height:1.55;overflow-wrap:anywhere}.response pre{position:relative;padding:14px;overflow:auto;border:1px solid #334155;border-radius:9px;background:#020617}.response code{font-family:Cascadia Code,Consolas,monospace}.copy-code{position:absolute;top:6px;right:6px;padding:4px 7px;font-size:11px}.hidden{display:none}ul,ol{padding-left:22px}a{color:#7dd3fc}
</style></head><body><main class="shell"><header class="head"><h1>Live Response</h1><span id="status" class="status">OFFLINE</span></header>
<section id="join" class="join"><label for="token">Enter sharing token</label><div class="row"><input id="token" autocomplete="one-time-code" maxlength="20" placeholder="XXXX-XXXX-XXXX"><button id="joinButton">Join</button></div><p id="error" class="error" role="alert"></p></section>
<section id="viewer" class="hidden"><div class="response-head"><button id="copy">Copy response</button></div><article id="response" class="response"><p>Waiting for an AI response…</p></article></section></main>
<script>
const joinPanel=document.querySelector('#join'),viewer=document.querySelector('#viewer'),tokenInput=document.querySelector('#token'),joinButton=document.querySelector('#joinButton'),error=document.querySelector('#error'),status=document.querySelector('#status'),response=document.querySelector('#response'),copy=document.querySelector('#copy');let socket=null,current='',joinedToken='',retry=null,ended=false;
const escapeHtml=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(md){const blocks=[];let text=escapeHtml(md).replace(/\`\`\`([\w+#.-]*)\n([\s\S]*?)\`\`\`/g,(_,lang,code)=>{const id=blocks.length;blocks.push('<pre><button class="copy-code" data-code="'+id+'">Copy Code</button><code>'+code+'</code></pre>');return '\n@@CODE'+id+'@@\n'});text=text.split(/\n{2,}/).map(part=>{const code=part.match(/^@@CODE(\d+)@@$/);if(code)return blocks[Number(code[1])];if(/^[-*] /m.test(part))return '<ul>'+part.split('\n').map(x=>'<li>'+x.replace(/^[-*] /,'')+'</li>').join('')+'</ul>';return '<p>'+part.replace(/\n/g,'<br>')+'</p>'}).join('');response.innerHTML=text||'<p>Waiting for an AI response…</p>';response.querySelectorAll('.copy-code').forEach(button=>button.onclick=()=>navigator.clipboard.writeText(button.nextElementSibling.textContent||''));}
function connect(){clearTimeout(retry);ended=false;status.textContent='CONNECTING';status.className='status';const protocol=location.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(protocol+'//'+location.host+'/ws?token='+encodeURIComponent(joinedToken));socket.onopen=()=>{error.textContent=''};socket.onmessage=e=>{const message=JSON.parse(e.data);if(message.type==='snapshot'){joinPanel.classList.add('hidden');viewer.classList.remove('hidden');status.textContent=message.streaming?'LIVE • STREAMING':'LIVE';status.className='status live';current=message.response||'';render(current)}else if(message.type==='response_start'){current='';status.textContent='LIVE • STREAMING';status.className='status live'}else if(message.type==='response_delta'){current+=message.delta;render(current)}else if(message.type==='response_complete'){status.textContent='LIVE';status.className='status live'}else if(message.type==='session_ended'){ended=true;status.textContent='ENDED';error.textContent=message.message;joinPanel.classList.remove('hidden');viewer.classList.add('hidden')}};socket.onclose=e=>{if(e.code===4003){error.textContent='Invalid or expired token.';status.textContent='OFFLINE';return}if(ended||e.code===4001)return;status.textContent='RECONNECTING…';retry=setTimeout(connect,1500)};socket.onerror=()=>socket.close()}
joinButton.onclick=()=>{joinedToken=tokenInput.value.trim();if(!joinedToken){error.textContent='Enter a sharing token.';return}connect()};tokenInput.onkeydown=e=>{if(e.key==='Enter')joinButton.click()};copy.onclick=()=>navigator.clipboard.writeText(current);
</script></body></html>`
